Repository projectunic0rn/warmr, pull requests merged in 2019-06, with the labels that each got.

#1 Implement basic API
  api/.env.example
  api/.gitignore
  api/.prettierrc
  api/README.md
  api/nest-cli.json
  api/nodemon-debug.json
  api/nodemon.json
  api/package-lock.json
  api/package.json
  api/src/config/database.ts
  api/src/config/server.ts
  api/src/main.ts
  api/src/modules/app.module.ts
  api/src/modules/auth/auth.controller.ts
  api/src/modules/auth/auth.module.ts
  api/src/modules/auth/auth.service.ts
  api/src/modules/auth/dto/auth-credentials.dto.ts
  api/src/modules/auth/jwt-payload.interface.ts
  api/src/modules/auth/jwt.strategy.ts
  api/src/modules/events/dto/create-event.dto.ts
  api/src/modules/events/dto/get-events-filter.dto.ts
  api/src/modules/events/dto/location.dto.ts
  api/src/modules/events/dto/update-event.dto.ts
  api/src/modules/events/event-status.enum.ts
  api/src/modules/events/event.entity.ts
  api/src/modules/events/event.repository.ts
  api/src/modules/events/events.controller.ts
  api/src/modules/events/events.module.ts
  api/src/modules/events/events.service.ts
  api/src/modules/events/pipes/event-status-validation.pipe.ts
  api/src/modules/events/util/location.ts
  api/src/modules/users/dto/create-user.dto.ts
  api/src/modules/users/dto/update-password.dto.ts
  api/src/modules/users/dto/update-user.dto.ts
  api/src/modules/users/get-user.decorator.ts
  api/src/modules/users/user.entity.ts
  api/src/modules/users/user.repository.ts
  api/src/modules/users/users.controller.ts
  api/src/modules/users/users.module.ts
  api/src/modules/users/users.service.ts
  api/test/app.e2e-spec.ts
  api/test/jest-e2e.json
  api/tsconfig.build.json
  api/tsconfig.json
  api/tslint.json
Labels: enhancement

#2 Set up initial React Native UI app
  ui/.gitignore
  ui/.watchmanconfig
  ui/App.js
  ui/app.json
  ui/assets/icon.png
  ui/assets/splash.png
  ui/babel.config.js
  ui/package-lock.json
  ui/package.json
  ui/screens/app-screens/homeScreen.js
  ui/screens/app-screens/profileScreen.js
  ui/screens/auth-screens/authLoadingScreen.js
  ui/screens/auth-screens/signInScreen.js
  ui/screens/auth-screens/signUpScreen.js
  ui/screens/auth-screens/welcomeScreen.js
  ui/services/authService.js
Labels: ui

#6 Update event entity + cleanup
  api/src/main.ts
  api/src/modules/app.module.ts
  api/src/modules/auth/auth.module.ts
  api/src/modules/events/dto/create-event.dto.ts
  api/src/modules/events/dto/get-events-filter.dto.ts
  api/src/modules/events/dto/location.dto.ts
  api/src/modules/events/dto/update-event.dto.ts
  api/src/modules/events/event.entity.ts
  api/src/modules/events/event.example.json
  api/src/modules/events/event.repository.ts
  api/src/modules/events/events.controller.ts
  api/src/modules/events/events.service.ts
  api/src/modules/events/pipes/event-status-validation.pipe.ts
  api/src/modules/events/types/criteria.interface.ts
  api/src/modules/events/types/event-status.enum.ts
  api/src/modules/events/types/location.interface.ts
  api/src/modules/events/types/place.interface.ts
  api/src/modules/events/util/location.ts
  api/src/modules/users/users.controller.ts
  api/src/modules/users/users.module.ts
  api/src/modules/users/users.service.spec.ts
  api/src/modules/users/users.service.ts
Labels: api, enhancement
